services:
  postgres:
    container_name: service-postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=allocation
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - allocation
          
  redis:
    container_name: service-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - allocation

  service-allocation:
    container_name: allocation
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=allocation
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PREFIX=${PREFIX:-~/.local}
    volumes:
      - .:/allocation:rw
      - conan_cache:/root/.conan2
    ports:
      - 8080:8080
    working_dir: /allocation
    depends_on:
      - postgres
      - redis
    networks:
      - allocation
    command: make start-service

networks:
  allocation:
    driver: bridge

volumes:
  conan_cache: