services:
  postgres:
    container_name: service-postgres
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432
    volumes:
      - ./postgresql/schemas:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    networks:
      - allocation
          
  redis:
    container_name: service-redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - allocation

  service-allocation:
    container_name: allocation
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PREFIX=${PREFIX}
    volumes:
      - .:/allocation:rw
      - conan_cache:/root/.conan2
    ports:
      - 8080:8080
    working_dir: /allocation
    depends_on:
      - postgres
      - redis
    networks:
      - allocation
    command: make start-release

networks:
  allocation:
    driver: bridge

volumes:
  conan_cache: