openapi: 3.0.0
info:
  title: Allocation Service
  description: Service for managing product batches and allocating customer orders
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /allocate:
    post:
      summary: Allocate an order line to a batch
      description: Allocate a customer order line to an available batch in the system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderid:
                  type: string
                  description: Unique identifier of the customer order
                  example: "order-123"
                sku:
                  type: string
                  description: Stock Keeping Unit (SKU) of the product
                  example: "RED-CHAIR"
                qty:
                  type: integer
                  description: Quantity of products to allocate
                  minimum: 1
                  example: 10
              required:
                - orderid
                - sku
                - qty
      responses:
        '202':
          description: Order line successfully allocated. Request accepted for processing.
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
        '409':
          description: Conflict — business rule violation (e.g., insufficient stock or concurrent update)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Could not serialize access due to concurrent update"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "AllocateHandler unknown exception"

  /add_batch:
    post:
      summary: Add a new product batch
      description: Register a new batch of products in the inventory system
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ref:
                  type: string
                  description: Reference identifier of the batch
                  example: "batch-001"
                sku:
                  type: string
                  description: Stock Keeping Unit (SKU) of the product
                  example: "RED-CHAIR"
                qty:
                  type: integer
                  description: Quantity of products in the batch
                  minimum: 1
                  example: 100
                eta:
                  type: string
                  format: date-time
                  description: Estimated time of arrival (optional, ISO 8601 format)
                  example: "2023-12-31T23:59:59Z"
              required:
                - ref
                - sku
                - qty
      responses:
        '201':
          description: Batch successfully added
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Batch added"
        '400':
          description: Invalid request payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "AddBatchHandler unknown exception"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Poco exception details"

  /allocations/{orderid}:
    get:
      summary: Retrieve allocations for a customer order
      description: Get allocation details for a specific customer order by order ID
      parameters:
        - name: orderid
          in: path
          description: Unique identifier of the customer order
          required: true
          schema:
            type: string
          example: "order-123"
      responses:
        '200':
          description: Successful response with allocation details
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sku:
                      type: string
                      description: Stock Keeping Unit (SKU) of the allocated product
                      example: "RED-CHAIR"
                    batchref:
                      type: string
                      description: Reference of the batch from which the product was allocated
                      example: "batch-001"
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid orderid"
        '404':
          description: Order not found or no allocations available
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Poco exception details"

  /ping:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      responses:
        '200':
          description: Service is healthy
