openapi: 3.0.0
info:
  title: allocation 1.0
  description: a backend application built with Poco
  version: 1.0.0
servers:
  - url: localhost:8080
    description: local

paths:
  /allocate:
    post:
      summary: Allocate products from a batch
      description: Allocate products from a batch to fulfill an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderUID:
                  type: string
                  description: The unique identifier of the order
                SKU:
                  type: string
                  description: The stock keeping unit of the product
                quantity:
                  type: integer
                  description: The quantity of products to allocate
                  minimum: 1
      responses:
        '201':
          description: Products have been successfully allocated
        '400':
          description: Bad request - invalid input

  /add_batch:
    post:
      summary: Add a new batch of products
      description: Add a new batch of products to the inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ref:
                  type: string
                  description: The reference identifier for the batch
                SKU:
                  type: string
                  description: The stock keeping unit of the product
                quantity:
                  type: integer
                  description: The quantity of products in the batch
                  minimum: 1
                eta:
                  type: string
                  format: date
                  description: The estimated time of arrival for the batch (optional)
      responses:
        '201':
          description: Batch has been successfully added
        '400':
          description: Bad request - invalid input

  /allocations/{orderUID}:
    get:
      summary: Get allocation details for an order
      description: Retrieve allocation details for a specific order
      parameters:
        - name: orderUID
          in: path
          description: The unique identifier of the order
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Order not found