openapi: 3.0.0
info:
  title: allocation 1.0
  description: a backend application built with Poco
  version: 1.0.0
servers:
  - url: localhost:8080
    description: local

paths:
  /allocate:
    post:
      summary: Allocate products from a batch
      description: Allocate products from a batch to fulfill an order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderUID:
                  type: string
                  description: The unique identifier of the order
                  example: "order-123"
                SKU:
                  type: string
                  description: The stock keeping unit of the product
                  example: "RED-CHAIR"
                quantity:
                  type: integer
                  description: The quantity of products to allocate
                  minimum: 1
                  example: 10
              required:
                - orderUID
                - SKU
                - quantity
      responses:
        '202':
          description: Products have been successfully allocated. Request accepted for processing.
        '400':
          description: Bad request - invalid input (e.g., missing fields, incorrect types).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
        '409':
          description: Conflict - business logic error (e.g., insufficient stock, no batch available).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Out of stock for SKU RED-CHAIR"
        '500':
          description: Internal Server Error - an unexpected error occurred on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Poco exception details"

  /add_batch:
    post:
      summary: Add a new batch of products
      description: Add a new batch of products to the inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ref:
                  type: string
                  description: The reference identifier for the batch
                  example: "batch-001"
                SKU:
                  type: string
                  description: The stock keeping unit of the product
                  example: "RED-CHAIR"
                quantity:
                  type: integer
                  description: The quantity of products in the batch
                  minimum: 1
                  example: 100
                eta:
                  type: string
                  format: date
                  description: The estimated time of arrival for the batch (optional)
                  example: "2023-12-31"
              required:
                - ref
                - SKU
                - quantity
      responses:
        '201':
          description: Batch has been successfully added.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Batch added"
        '400':
          description: Bad request - invalid input (e.g., missing fields, incorrect types).
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid input data"
        '500':
          description: Internal Server Error - an unexpected error occurred on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Poco exception details"

  /allocations/{orderUID}:
    get:
      summary: Get allocation details for an order
      description: Retrieve allocation details for a specific order
      parameters:
        - name: orderUID
          in: path
          description: The unique identifier of the order
          required: true
          schema:
            type: string
          example: "order-123"
      responses:
        '200':
          description: Successful response with allocation details.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sku:
                      type: string
                      description: The SKU of the allocated product.
                      example: "RED-CHAIR"
                    batchref:
                      type: string
                      description: The reference of the batch from which the product was allocated.
                      example: "batch-001"
        '400':
          description: Bad request - invalid orderUID (e.g., empty).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid orderId"
        '404':
          description: Order not found or no allocations for the specified orderUID.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "not found"
        '500':
          description: Internal Server Error - an unexpected error occurred on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Poco exception details"
  /ping:
    get:
      summary: Health check endpoint
      description: Checks the status of the service.
      responses:
        '200':
          description: Service is healthy.