#pragma once

#include <algorithm>
#include <atomic>
#include <barrier>
#include <chrono>
#include <exception>
#include <format>
#include <functional>
#include <iostream>
#include <mutex>
#include <numeric>
#include <queue>
#include <ranges>
#include <shared_mutex>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <typeindex>
#include <unordered_set>
#include <utility>
#include <vector>

/// Poco
#include <Poco/Data/PostgreSQL/Connector.h>
#include <Poco/Data/RecordSet.h>
#include <Poco/Data/SessionPool.h>
#include <Poco/Delegate.h>
#include <Poco/Environment.h>
#include <Poco/File.h>
#include <Poco/JSON/Object.h>
#include <Poco/JSON/Parser.h>
#include <Poco/Net/HTTPClientSession.h>
#include <Poco/Net/HTTPRequest.h>
#include <Poco/Net/HTTPRequestHandler.h>
#include <Poco/Net/HTTPRequestHandlerFactory.h>
#include <Poco/Net/HTTPServer.h>
#include <Poco/Net/HTTPServerParams.h>
#include <Poco/Net/HTTPServerRequest.h>
#include <Poco/Net/HTTPServerResponse.h>
#include <Poco/Net/ServerSocket.h>
#include <Poco/Redis/AsyncReader.h>
#include <Poco/Redis/Command.h>
#include <Poco/Redis/Redis.h>
#include <Poco/Redis/Type.h>
#include <Poco/UUIDGenerator.h>
#include <Poco/Util/HelpFormatter.h>
#include <Poco/Util/ServerApplication.h>
