#pragma once

#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <exception>
#include <format>
#include <functional>
#include <iostream>
#include <list>
#include <mutex>
#include <numeric>
#include <queue>
#include <ranges>
#include <shared_mutex>
#include <sstream>
#include <string>
#include <string_view>
#include <thread>
#include <tuple>
#include <typeindex>
#include <unordered_set>
#include <utility>
#include <vector>


/// Poco
#include <Poco/Data/Connector.h>
#include <Poco/Data/PostgreSQL/Connector.h>
#include <Poco/Data/SessionImpl.h>
#include <Poco/Data/SessionPool.h>
#include <Poco/Data/StatementImpl.h>
#include <Poco/Data/Transaction.h>
#include <Poco/Delegate.h>
#include <Poco/File.h>
#include <Poco/JSON/Object.h>
#include <Poco/JSON/Parser.h>
#include <Poco/Net/HTTPClientSession.h>
#include <Poco/Net/HTTPRequest.h>
#include <Poco/Net/HTTPResponse.h>
#include <Poco/Redis/AsyncReader.h>
#include <Poco/Redis/Client.h>
#include <Poco/Redis/Command.h>
#include <Poco/Redis/Redis.h>
#include <Poco/Redis/Type.h>
#include <Poco/StreamCopier.h>
#include <Poco/URI.h>
#include <Poco/UUIDGenerator.h>
#include <Poco/Util/HelpFormatter.h>
#include <Poco/Util/IniFileConfiguration.h>
#include <Poco/Util/Subsystem.h>

#include "Poco/Data/RecordSet.h"
#include "Poco/Data/SQLite/Connector.h"
#include "Poco/Data/Session.h"
#include "Poco/Net/HTTPRequestHandler.h"
#include "Poco/Net/HTTPRequestHandlerFactory.h"
#include "Poco/Net/HTTPServer.h"
#include "Poco/Net/HTTPServerParams.h"
#include "Poco/Net/HTTPServerRequest.h"
#include "Poco/Net/HTTPServerResponse.h"
#include "Poco/Net/ServerSocket.h"
#include "Poco/Util/ServerApplication.h"
