#pragma once

#include <string>
#include <list>
#include <vector>
#include <unordered_set>
#include <algorithm>
#include <chrono>
#include <utility>
#include <functional>
#include <exception>
#include <string_view>
#include <format>
#include <numeric>
#include <sstream>
#include <mutex>


/// Poco
#include "Poco/Data/Session.h"
#include "Poco/Data/SQLite/Connector.h"
#include "Poco/Data/RecordSet.h"
#include "Poco/Util/ServerApplication.h"
#include <Poco/Net/HTTPClientSession.h>
#include "Poco/Net/HTTPServerParams.h"
#include <Poco/Net/HTTPRequest.h>
#include <Poco/Net/HTTPResponse.h>
#include "Poco/Net/ServerSocket.h"
#include "Poco/Net/HTTPRequestHandlerFactory.h"
#include "Poco/Net/HTTPRequestHandler.h"
#include "Poco/Net/HTTPServerResponse.h"
#include "Poco/Net/HTTPServer.h"
#include "Poco/Net/HTTPServerRequest.h"
#include <Poco/JSON/Object.h>
#include <Poco/JSON/Parser.h>
#include <Poco/StreamCopier.h>
#include <Poco/UUIDGenerator.h>
#include <Poco/Data/SessionPool.h>
#include <Poco/Data/SessionImpl.h>
#include <Poco/Data/StatementImpl.h>
#include <Poco/Data/Connector.h>
#include <Poco/Util/HelpFormatter.h>
#include <Poco/Util/IniFileConfiguration.h>
#include <Poco/URI.h>
