name: allocation CI

'on':
    schedule:
      - cron: '30 5 * * 1'  # Every Monday at 5:30
    pull_request:
    push:
        branches:
          - main
          - develop

env:
    UBSAN_OPTIONS: print_stacktrace=1

jobs:
    posix:
        strategy:
            fail-fast: false
            matrix:
              - os: ubuntu-24.04
                make-target: test-debug
                compiler: g++-14
                description: "Debug build"
              
              - os: ubuntu-24.04
                make-target: test-release
                compiler: g++-14
                description: "Release build"

        name: '${{matrix.os}}: ${{matrix.info}}'
        runs-on: ${{matrix.os}}

        steps:
          - uses: actions/checkout@v4

          - name: Reuse ccache directory
            uses: actions/cache@v4
            with:
                path: ~/.cache/ccache
                key: '${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-${{github.run_number}}'
                restore-keys: |
                    ${{matrix.os}} ${{matrix.info}} ccache-dir ${{github.ref}} run-'
                    ${{matrix.os}} ${{matrix.info}} ccache-

          - name: Install packages
            run: |
                sudo apt update
                sudo apt install -y build-essential cmake pipx pycodestyle postgresql
                pipx ensurepath
                pipx install conan
                PATH="/root/.local/bin:${PATH}"
   
          - name: Reinstall postgres 14
            run: |
                sudo apt purge libpq5 libpq-dev postgresql-*
                sudo apt install -y postgresql-14 postgresql-client-14 postgresql-server-dev-14

          - name: Install Redis
            run: |
                sudo apt install -y redis-server
                sudo systemctl start redis.service
                sudo systemctl status redis.service
                redis-cli ping
                
          - name: Setup ccache
            run: |
                ccache -M 2.0GB
                ccache -s

          - name: Run postgresql
            if: matrix.make == 'test-release'
            run: |
                pg_lsclusters
                sudo -u postgres psql --command="CREATE USER allocation_user PASSWORD 'password'" --command="\du"
                sudo -u postgres createdb --owner=allocation_user allocation_db-1

          - name: Run migrations
            if: matrix.make == 'test-release'
            run: |
                PGPASSWORD=password psql 'postgresql://allocation@localhost:5432/allocation_db-1' -f ./postgresql/schemas/db-1.sql

          - name: Run ${{matrix.make}}
            run: |
                make ${{matrix.make}}

          - name: Test install ${{matrix.make}}
            if: matrix.make == 'test-release'
            run: |
                make dist-clean
                make install PREFIX=`pwd`/local_installation/

#          - name: Test run after install
#            if: matrix.make == 'test-release'
#            run: |
#               ./local_installation/bin/realmedium_sample \
#                   --config=./local_installation/etc/realmedium_sample/config.yaml \
#                   --config_vars=./local_installation/etc/realmedium_sample/config_vars.yaml \
#                   &

          - name: Check work run service
            if: matrix.make == 'test-release'
            run: |
                ps aux | grep allocation | grep config && curl http://localhost:8080/ping -v

          - name: Stop all
            if: matrix.make == 'test-release'
            run: |
                killall allocation

