jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            make-target: test-debug
            compiler: g++-14
            description: "Debug build"
          
          - os: ubuntu-24.04
            make-target: test-release
            compiler: g++-14
            description: "Release build"

    runs-on: ${{matrix.os}}

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: allocation
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user -d allocation"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake pipx pycodestyle
          pipx ensurepath
          pipx install conan
          export PATH="/root/.local/bin:$PATH"

      - name: Wait for Postgres
        run: |
          until pg_isready -h postgres -U user -d allocation; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run migrations
        run: |
          PGPASSWORD=password psql \
            "postgresql://user:password@postgres:5432/allocation" \
            -f ./postgresql/schemas/db-1.sql

      - name: Run build
        run: make ${{matrix.make-target}}

      - name: Test install
        if: matrix.make-target == 'test-release'
        run: |
          make dist-clean
          make install PREFIX=`pwd`/local_installation/

      - name: Test run after install
        if: matrix.make-target == 'test-release'
        run: |
          ./local_installation/bin/allocation &
          sleep 5

      - name: Check service
        if: matrix.make-target == 'test-release'
        run: |
          ps aux | grep allocation | grep config
          curl http://localhost:8080/ping -v

      - name: Run e2e test
        run: make e2e-test

      - name: Stop all
        if: matrix.make-target == 'test-release'
        run: killall allocation
