name: allocation Docker build

'on':
    schedule:
      - cron: '30 5 * * 1'  # Every Monday at 5:30
    pull_request:
    push:
        branches:
          - main
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Install docker-compose
            run: |
                sudo apt update
                sudo apt install -y docker-compose python3 python3-pip

          - name: Cmake
            run: |
                make docker-cmake-release
                sudo make dist-clean

          - name: Build
            run: make docker-build-release

          - name: Run test
            run: make docker-test-release

          - name: Run e2e tests
            run: make e2e-test
