name: allocation Docker build

'on':
    schedule:
      - cron: '30 5 * * 1'  # Every Monday at 5:30
    pull_request:
    push:
        branches:
          - main
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Install docker-compose
            run: |
                sudo apt update
                sudo apt install -y docker-compose python3 python3-pip

          - name: Cmake
            run: |
                make docker-cmake-release
                sudo make dist-clean

          - name: Build
            run: make docker-build-release

          - name: Run test
            run: make docker-test-release

          - name: Run service and e2e tests
            env:
              API_URL: http://localhost:8080
              REDIS_HOST: redis
              REDIS_PORT: 6379
            run: |
              make docker-start-service-debug-bg
              echo "Waiting for service..."
              sleep 60
              curl http://localhost:8080/ping -v
              make e2e-test
