name: allocation Docker build

'on':
    schedule:
      - cron: '30 5 * * 1'  # Every Monday at 5:30
    pull_request:
    push:
        branches:
          - main
          - master
          - develop
          - feature/**

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Install docker-compose
            run: |
                sudo apt update
                sudo apt install -y docker-compose

          - name: Cmake
            run: make docker-cmake-release

          - name: Build
            run: |
                rm -rf build 
                make docker-build-release

#          - name: Run tests
#            run: make docker-test-release
